# Generated by Django 5.1.4 on 2024-12-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.AddField(
            model_name='song',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=22),
        ),
    ]
