# Generated by Django 5.1.4 on 2024-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_song_user_song_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='sing_name',
            field=models.URLField(max_length=2000),
        ),
    ]
